### ISSUE TITLE
Reset password. The app allows saving passwords that do not meet the requirements.

### ISSUE THREAD

**Issue by TetianaPerinha** [Sunagatov/Iced-Latte#268]
**Description:** According to the requirements password must be at least 8 characters long and contain at least one letter, one digit, and may include special characters @$!%*?&.

**Precondition:** User is registered

**Step to reproduce:**

Execute the POST request as below. Replace code and email with valid data.

curl --location 'http://0.0.0.0:8083/api/v1/auth/password/change'
--header 'Content-Type: application/json'
--data-raw '{
"email": "email to resent password",
"code": "code to reset password",
"password": "t"
}'

**Expected result:** App should reject password, HTTP status code = 400, error message = ”Password must be at least 8 characters long and contain at least one letter, one digit, and may include special characters @$!%*?&")”.

**Actual result:** The app allows saving password that do not meet requirements, HTTP status code = 200

![image](https://github.com/Sunagatov/Iced-Latte/assets/68566253/d1e39f11-5230-417f-981d-09b3a50cac67)
![image](https://github.com/Sunagatov/Iced-Latte/assets/68566253/22bf1171-c15c-455f-a4bf-1e0214cd5557)

**Comment by anmol797** [comment]
hi , can i work on this issue ?
