### ISSUE TITLE
(MAIN PAGE-PRODUCT'S CATALOG) incorrect order of products when sorted by average rating

### ISSUE THREAD

**Issue by Lightness322** [Sunagatov/Iced-Latte#291]
**Before:**

1. When sorting with parameters: 'sort_attribute=averageRating&sort_direction=desc' we get a list of products that first contains products with _averageRating_ equal to _null_.
2. When sorting with parameters: 'sort_attribute=averageRating&sort_direction=asc' we get a list of products that last contains products with _averageRating_ equal to _null_.

**After:**

1. Descending order: Products with _averageRating_ equal to _null_ should be the latest.
2. Ascending order: Products with _averageRating_ equal to _null_ should come first.

**Comment by ilsinyakov** [comment]
Tested.
Approved.

**Comment by TetianaPerinha** [comment]
Fixed.
