### ISSUE TITLE
(MAIN PAGE-PRODUCT'S CATALOG) incorrect data: rating and reviews count

### ISSUE THREAD

**Issue by Lightness322** [Sunagatov/Iced-Latte#294]
![image](https://github.com/Sunagatov/Iced-Latte/assets/126592923/0236cfa8-145a-4231-9016-651a6df67de2)
![image](https://github.com/Sunagatov/Iced-Latte/assets/126592923/84522928-4aea-4b42-b902-6eff73390b5e)

After we **deleted** the review on the product page, the data (avgRating and reviewsCount) that we get with request _'/{productId}/reviews/statistics'_ **changes**
But
The data (averageRating and reviewsCount) that we get with request _'/products'_ **does not change**

**Comment by Sunagatov** [comment]
Fixed.

**Comment by ilsinyakov** [comment]
Tested.
Approved.

**Comment by TetianaPerinha** [comment]
fixed
