### ISSUE TITLE
 GET product reviews request with an invalid value of param "product_rating" the system returns all product reviews

### ISSUE THREAD

**Issue by TetianaPerinha** [Sunagatov/Iced-Latte#329]
Describe the bug
When sending a GET product reviews request with an invalid value of param "product_rating" the system returns all product reviews

To Reproduce
Send the GET request as below use value for param product_rating = %

curl --location '[https://iced-latte.uk/backend/api/v1/products/e6a4d7f2-d40e-4e5f-93b8-5d56ce6724c5/reviews?page={value}]([https://iced-latte.uk/backend/api/v1/products/e6a4d7f2-d40e-4e5f-93b8-5d56ce6724c5/reviews?size={value}](https://iced-latte.uk/backend/api/v1/products/e6a4d7f2-d40e-4e5f-93b8-5d56ce6724c5/reviews?product_rating={value}

Expected behavior
The system should reject the request with 400 HTTP Status code "error": "Bad Request".

Actual result
System accept the request and returns all product reviews.

<img width="1168" alt="get all reviews with param product_ratings = %" src="https://github.com/Sunagatov/Iced-Latte/assets/68566253/bfb7f548-0b23-44a6-9f2f-767d7fe0242a">

**Comment by Prankurtiwari** [comment]
Hi TetianaPerinha, Can you assign this issue to me ??? Or is it okay if i start working on this ??
Please let me know in any case. 
TBH I am contributing to Open Source for the first time so I am unaware of the protocols.

**Comment by Prankurtiwari** [comment]
Hi TetianaPerinha, I have raised the initial [PR](https://github.com/Sunagatov/Iced-Latte/pull/330). Please review

**Comment by TetianaPerinha** [comment]
> Hi TetianaPerinha, I have raised the initial [PR](https://github.com/Sunagatov/Iced-Latte/pull/330). Please review

@Sunagatov Please review the pr

**Comment by Prankurtiwari** [comment]
Hi @TetianaPerinha & @Sunagatov Please review my [PR ](https://github.com/Sunagatov/Iced-Latte/pull/330), it's been pending from last week.
Thank you
